title: Junhan Fang
position: PostDoc Fellow
affiliation: Center for Methods in Implementation and Prevention Science
email: junhan.fang[at]yale[dot]edu
keywords: minimal academic
avatar: /assets/img/Junhan_Fang_photo.jpeg
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
remote_theme: yaoyao-liu/minimal-light


